### ISSUE TITLE
在api网关层无法读取nacos配置

### ISSUE THREAD

**Issue by zhengzhishanliang** [Double-Jin/jin-microservices#2]
您好，冒昧打扰，请见谅。
我是在虚拟机上操作的，MYSQL和REDIS我是原生安装，其余的都是按照您的文档使用docker安装。安装完每个服务的url都可以正常访问，但在启动php bin/hyperf.php start 时，报了：The config of nacos_config read failed from Nacos 错误。
其余配置和状态信息截图如下，希望能获取到指点，谢谢！
![1655433853416](https://user-images.githubusercontent.com/50315515/174214540-6373caae-da4c-4166-9c5a-7fd145cc4f24.png)
![1655433888441](https://user-images.githubusercontent.com/50315515/174214594-2e90c126-8e2f-4418-a9e8-ccc0d1229873.png)
![1655433940910](https://user-images.githubusercontent.com/50315515/174214694-8744c480-4e2d-419b-8e4b-79d4e87396a7.png)
![1655434017487](https://user-images.githubusercontent.com/50315515/174214836-3b12cc1a-f33b-4b1d-b6cf-0a9c518bf07f.png)

**Comment by Double-Jin** [comment]
需要按照我写的nacos配置文档导入这个配置文件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhengzhishanliang ***@***.***&gt;
发送时间: 2022年6月17日 10:47
收件人: Double-Jin/jin-microservices ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Double-Jin/jin-microservices] 在api网关层无法读取nacos配置 (Issue #2)





 
您好，冒昧打扰，请见谅。
 我是在虚拟机上操作的，MYSQL和REDIS我是原生安装，其余的都是按照您的文档使用docker安装。安装完每个服务的url都可以正常访问，但在启动php bin/hyperf.php start 时，报了：The config of nacos_config read failed from Nacos 错误。
 其余配置和状态信息截图如下，希望能获取到指点，谢谢！
