### ISSUE TITLE
不知道是我.env配置错误还是别的问题，user服务启动时报错

### ISSUE THREAD

**Issue by Magr7** [Double-Jin/jin-microservices#3]
![image](https://user-images.githubusercontent.com/48614892/176631738-a5d13c9d-5595-4750-9223-7b92623f8db3.png)
![image](https://user-images.githubusercontent.com/48614892/176631852-57520d79-12be-4922-9c00-6385e2fae8fb.png)

**Comment by Double-Jin** [comment]
看起来像nacos连接的问题，nacos_host是不是没配对

**Comment by Magr7** [comment]
好嘞 我检查下，谢啦 api-getway nacos同样的配置可以正常启动

**Comment by Double-Jin** [comment]
微信号: DoubleJin_ 
有问题可以加下我
